# Generated by Django 4.2.5 on 2023-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_image_predicted_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
